# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e59608bc778edc2ea95984cf1527c96bf124cec53ce69c004451b01f606210ddb2aaca2561a0404a5138dc12067cf6089a8257222a8e583e73d491bf755f346b

test:
  secret_key_base: 9f4fbc48de2e94602972ff73671ba39f2cbd7d9510a1275df5c3367115e3381c5269a7140b2c3bf489b40a79f483bf1d02bf38332504170d6bd959ddb90e1d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
